stages:
  - build
  - test
  - deploy

build:
  image: node:18-alpine
  stage: build
  rules: 
    - if:
      changes:
        - utils/*.ts
        - pacakge*.json
  script:
    - npm install
    - npm run build

test:
  image: node:latest
  stage: test
  rules: 
    - if:
      changes:
        - utils/*.ts
  script:
    - npm install
    - npm run test

deploy:
  image: node:18-alpine
  stage: deploy
  before_script:
    - apk add rsync openssh
    - npm install
    - npm run build
    - eval $(ssh-agent -s)
    - echo "${ID_RSA}" | tr -d '\r' | ssh-add -
  script:
    - rsync -e "ssh -o StrictHostKeyChecking=no" -arvc dist/* $SERVER_USER@$SERVER_IP:/home/ec2-user
  rules:
  - when: manual
