const SET_ALL_ELEM = "SET_ALL_ELEM";
const SET_ALL_GUILD = "SET_ALL_GUILD";
const SET_ALL_ROOM = "SET_ALL_ROOM";
const SET_ALL_ROOM_ITEMS = "SET_ALL_ROOM_ITEMS";

const ADD_GUILD = "ADD_GUILD";
const ADD_ROOM = "ADD_ROOM";
const ADD_ROOM_ITEMS = "ADD_ROOM_ITEMS";

const PUSH_GUILD = "PUSH_GUILD";

export {
    SET_ALL_ELEM,
    SET_ALL_GUILD,
    SET_ALL_ROOM,
    SET_ALL_ROOM_ITEMS,

    ADD_GUILD,
    ADD_ROOM,
    ADD_ROOM_ITEMS,

    PUSH_GUILD
}